### ISSUE TITLE
Can't enable node in Node-Red  0.18.x

### ISSUE THREAD

**Issue by sorgens** [bartbutenaers/node-red-contrib-multipart-stream-encoder#2]
Hi,

Seems that I can't add this node because of UnexpectedToken error:

1, Instalation logs:

```
pi@homebridge:~/.node-red $ sudo npm install node-red-contrib-multipart-stream-encoder
node-red-project@0.0.1 /home/pi/.node-red
└── node-red-contrib-multipart-stream-encoder@0.0.2

npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.
pi@homebridge:~/.node-red $ node-red-stop
```

2. Node-Red :

```
29 Mar 07:45:12 - [info] Settings file  : /home/pi/.node-red/settings.js
29 Mar 07:45:12 - [info] User directory : /home/pi/.node-red
29 Mar 07:45:12 - [warn] Projects disabled : set editorTheme.projects.enabled=true to enable
29 Mar 07:45:12 - [info] Flows file     : /home/pi/.node-red/flows_homebridge.json
29 Mar 07:45:12 - [info] Server now running at https://127.0.0.1:1880/
29 Mar 07:45:12 - [info] Starting flows
29 Mar 07:45:13 - [info] Started flows
29 Mar 07:45:13 - [info] [mqtt-broker:69a3a9f2.caecd8] Connected to broker: mqtt://127.0.0.1:1883
29 Mar 07:47:06 - [info] Stopping flows
29 Mar 07:47:07 - [info] [mqtt-broker:69a3a9f2.caecd8] Disconnected from broker: mqtt://127.0.0.1:1883
29 Mar 07:47:07 - [info] Stopped flows
29 Mar 07:47:07 - [info] Starting flows
29 Mar 07:47:07 - [info] Started flows
29 Mar 07:47:07 - [info] [mqtt-broker:69a3a9f2.caecd8] Connected to broker: mqtt://127.0.0.1:1883
29 Mar 07:50:25 - [warn] Failed to enable node:
29 Mar 07:50:25 - [warn]  - multipart-encoder : SyntaxError: Unexpected token [
```

Best Regarrds

**Comment by bartbutenaers** [comment]
Hi Piotr,

Back from work ...

Very weird problem that you have registered.  
I have uninstalled my contribution, reinstalled it again and can start Node-Red without SyntaxError:
![image](https://user-images.githubusercontent.com/14224149/38107571-9bdade46-3392-11e8-9c10-5233dfc26224.png)

Could it perhaps be that you are running an **older NodeJs version**.  As you can seen in the screenshot, I'm running version 8.9.0.  Perhaps I'm using something in version 0.0.2 of my encoder, that doesn't exist on older NodeJs versions.

But the problem is that the SyntaxError doesn't inform about the line number, so I can only start guessing...

Kind regards,
Bart

**Comment by sorgens** [comment]
Hi Bard,

It was node.js version.

I got 
```
pi@homebridge:~ $ node -v
v5.10.0
```
After update - everything works ! Thanks

Best Regards

**Comment by bartbutenaers** [comment]
Hi,
glad it is solved.  And thanks for the feedback !
Bart
