### ISSUE TITLE
Where are the images output to?

### ISSUE THREAD

**Issue by asd-macl** [bartbutenaers/node-red-contrib-multipart-stream-encoder#6]
I don't know if I'm missing something, but I copied the example for "Same stream to 'all clients'" into a new flow (replacing the missing interval node with a regular inject that repeats every 1 second) and can't find where my video receiver software should be looking to receive the image. Is this to be set up outside of the given flow?

Thanks

**Comment by bartbutenaers** [comment]
Hi @asd-macl,

Sorry for the delay, was a busy week...

Yes indeed you need to replace the interval node, since the example flows are already quite old.

You can also add a [node-red-contrib-image-output](https://flows.nodered.org/node/node-red-contrib-image-output) node to your flow, to preview whether your images are good:

![multipart_encoder2](https://user-images.githubusercontent.com/14224149/160213149-c5cc23b0-6f8d-4225-965a-b4856773a771.gif)

So in this case the flow is running on my https://localhost:1880.  You see in the above flow that there is a http-in node listening to the path "/infinite".  Which means that if you navigate to https://localhost:1880/infinite, your http request will arrive at the output of the http-in node, so it will be injected into the multipart-stream-encoder node (which will send the images to your browser):

![multipart_encoder](https://user-images.githubusercontent.com/14224149/160213344-c1faa555-7a7c-4066-bd49-b5fab54b2894.gif)

Of course you should replace localhost by the hostname where your Node-RED flow is running....

Is that a bit clear?

**Comment by asd-macl** [comment]
Yes, I'm able to see the images on their own page now. Thank you!
